#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e ncmpcpp ;;
	2) mpc toggle ;;  # right click, pause/unpause
	3) mpc status ; notify-send "🎵 Music module" "\- Shows mpd song playing.
- ⏸  when paused.
- Left click opens ncmpcpp.
- Middle click pauses.
- Scroll changes track.";;
	4) mpc volume +1 ;; # scroll up, previous
	5) mpc volume -1 ;;  # scroll down, next
	10) setsid -f "$TERMINAL" -e "$EDITOR" $0 ;;
	12) setsid -f "$TERMINAL" -e "$EDITOR" $STATUSSCRIPTS/display/sb-music ;;
esac

duskc --ignore-reply run_command setstatus $BLOCK_STATUS "$(sb-music)"
