#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f pavucontrol ;;
	2) mic-toggle ;;
	3) notify-send "🎤 Microphone module" "\- Shows microphone status  if muted and  if not.
- Middle click to mute." ;;
	10) setsid -f "$TERMINAL" -e "$EDITOR" $0 ;;
	12) setsid -f "$TERMINAL" -e "$EDITOR" $STATUSSCRIPTS/display/sb-microphone ;;
esac
