#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e neomutt ;;
  2) setsid -f mw -Y >/dev/null ;;
	3) notify-send " Mail module" "\- Shows unread mail
- Shows   if syncing mail
- Left click opens neomutt
- Middle click syncs mail" ;;
	10) setsid -f "$TERMINAL" -e "$EDITOR" $0 ;;
	12) setsid -f "$TERMINAL" -e "$EDITOR" $STATUSSCRIPTS/display/sb-mailbox ;;
esac

duskc --ignore-reply run_command setstatus $BLOCK_STATUS "$(sb-mailbox)"
