#!/bin/sh

case $BLOCK_BUTTON in
1) pomodoro -k; pomodoro -s Work ;;
2) pomodoro -k ;; # right click, pause/unpause
3) notify-send " Pomodoro module" "\- Shows current pomodoro timer
- Left click to start the 30min timer.
- Middle click to stop and reset the timer." ;;
# 4)  ;;
# 5)  ;;
10) setsid -f "$TERMINAL" -e "$EDITOR" $0 ;;
12) setsid -f "$TERMINAL" -e "$EDITOR" $STATUSSCRIPTS/display/sb-pomodoro ;;
esac

sleep 0.5
sb-pomodoro
