#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e sb-popupgrade ;;
	2) notify-send "$(/usr/bin/pacman -Qu)" ;;
	3) notify-send " Upgrade module" " : number of upgradable packages
- Left click to upgrade packages
- Middle click to show upgradable packages" ;;
	10) "$TERMINAL" -e "$EDITOR" $0 ;;
	12) "$TERMINAL" -e "$EDITOR" $STATUSSCRIPTS/display/sb-pacpackages ;;
esac
