#!/bin/sh
SETSTATUS="duskc --ignore-reply run_command setstatus"
pamixer --list-sources | grep input | awk '{print $1}' |
	while read -r index; do
		mic_muted="$(pamixer --source "$index" --get-mute)"

		if [ "$mic_muted" = "true" ]; then
			pamixer --source "$index" -u
      setsid -f canberra-gtk-play -i audio-volume-change
      $SETSTATUS 6 "$(sb-microphone)"
		else
			pamixer --source "$index" -m
      setsid -f canberra-gtk-play -i audio-volume-change
      $SETSTATUS 6 "$(sb-microphone)"
		fi
	done
