#!/bin/sh
BNESS=$(xbacklight -get)
toggle_brightness() {
	[ "$BNESS" -gt "70" ] && xbacklight -set 1 -fps 30
	[ "$BNESS" -lt "20" ] && xbacklight -set 25 -fps 30
	([ "$BNESS" -lt "70" ] && [ "$BNESS" -gt "20" ]) && xbacklight -set 75 -fps 30
}

case $BUTTON in
1) toggle_brightness ;;
2) xbacklight -set 1 -fps 30 ;;
3) notify-send "🔆 Brightness module" "Displays brightness level
- Left click to toggle brightness
- Middle click to set at minimum brightness
- Scroll to change." ;;
4) xbacklight -inc 1 -time 0 ;;
5) xbacklight -dec 1 -time 0 ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" $0 ;;
esac

if [ "$BNESS" -gt "70" ]; then
	icon=""
else
	icon=""
fi

echo "$icon $BNESS"
