#!/bin/sh
echo "$(shotkey-mode mode)"

case $BUTTON in
1) setsid -f "$TERMINAL" ;;
3) notify-send "⌨️ Shotkey modes module" "\- Display the current key binds mode
NormalMode: ⌨️  
$(awk -F'\\[|\\]|=|\"' '/ModeProperties mode_properties/,/};/ { printf("%s: %s\n", $2, $5)}' $HOME/.local/src/shotkey/config.h | sed '1d;$d' )" ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" $0 ;;
esac
