#!/bin/sh

pidof -x sb-mpdup >/dev/null 2>&1 || sb-mpdup >/dev/null 2>&1 &

case $BUTTON in
	1) setsid -f "$TERMINAL" -e ncmpcpp ;;
	2) mpc toggle ;;  # right click, pause/unpause
	3) mpc status ; notify-send "🎵 Music module" "\- Shows mpd song playing.
- ⏸  when paused.
- Left click opens ncmpcpp.
- Middle click pauses.
- Scroll changes track.";;
	4) mpc volume +1   ;;  # scroll up, previous
	5) mpc volume -1   ;;  # scroll down, next
	6) setsid -f "$TERMINAL" -e "$EDITOR" $0 ;;
esac
#
# Displays the current song being played on mpd

# ARTIST=$(mpc current -f %artist%)
SONG=$(mpc current -f %title% | cut -c -25)
LENGTH=$(echo "${#SONG}")

if [ "$LENGTH" -gt "24" ]; then
  SONG=$(echo "${SONG}..")
fi

STATUS=$(mpc status | grep -o '\[.*\]')
VOLUME=$(mpc volume | grep -o '[0-9]\+')

if [ "$VOLUME" -gt "70" ]; then
	VOL=""
elif [ "$VOLUME" -lt "20" ]; then
	VOL=""
else
	VOL=""
fi

[ "$STATUS" = "[paused]" ] && VOL=""

[ -n "$SONG" ] && echo "$SONG $VOL $VOLUME%"
