#!/bin/sh
index=$(pamixer --list-sources | awk '/input/ {print $1}')
mic_muted="$(pamixer --source "$index" --get-mute)"
[ "$mic_muted" = "true" ] && echo "" || echo ""

case $BUTTON in
	1) setsid -f pavucontrol ;;
	2) mic-toggle ;;
	3) notify-send "🎤 Microphone module" "\- Shows microphone status ❎ if muted and ⭕ if not.
- Middle click to mute." ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" $0 ;;
esac
