#!/bin/sh

# period="$(redshift -p | awk '$0 ~ "Period" {print $2}')"
temperature="$(redshift -p | awk '$0 ~ "Color temperature" {print $3}')"
period="$(redshift -p | awk '$0 ~ "Period" {print $2}')"

[ $period = "Night" ] && icon=""
[ $period = "Transition" ] && icon=""
[ $period = "Daytime" ] && icon=""

toggleredshift() {
	pidof redshift >/dev/null && killall redshift || setsid redshift
}

case $BUTTON in
1) notify-send "$(redshift -p)" ;;
2) toggleredshift ;;
# 4)  ;;
# 5)  ;;
3) notify-send "💡 Redshift module" "\- Displays current redshift status
- 🌙 at night.
- 💡 during transition phase.
- ☀  when it is day time." ;;
6) setsid -f "$TERMINAL" -e "$EDITOR" $0 ;;
esac

pidof redshift >/dev/null && echo "$icon $temperature" || echo "  "
