#!/bin/sh

# period="$(redshift -p | awk '$0 ~ "Period" {print $2}')"
temperature="$(redshift -p | awk '$0 ~ "Color temperature" {print $3}')"
period="$(redshift -p | awk '$0 ~ "Period" {print $2}')"

case $period in
  "Night") icon="🌙" ;;
  "Transition") icon="💡" ;;
  "Daytime") icon="☀️" ;;
esac

pidof redshift >/dev/null && echo "$icon$temperature" || echo "💡"
